-- FanRank v20: contenido curado suficiente para que cada perfil tenga un Top 10 real.
-- Integridad: son propuestas sustantivas, no popularidad fingida. Todas nacen con
-- web_votes=0, origin_upvotes=0 y sin source_url cuando no existe una fuente exacta.
-- Idempotencia: section + title evita duplicar una semilla si la migración se reintenta.

insert into public.fr_ideas
  (section, title, title_es, ai_score, ai_reason, ai_reason_es,
   approved, web_votes, origin_upvotes)
select v.section, v.title, v.title_es, v.ai_score, v.ai_reason, v.ai_reason_es,
       true, 0, 0
from (values
  -- FanRank: 4 existentes + 6 = 10.
  ('fanrank',
   'Verified creators can open a 48-hour response event',
   'Que los creadores verificados puedan abrir un evento de respuesta de 48 horas',
   91,
   'Adds a public consequence to voting while keeping authority explicit.',
   'Da una consecuencia pública al voto sin fingir quién tiene autoridad.'),
  ('fanrank',
   'Notify me only if the creator reacts to my idea',
   'Avísame solo si el creador reacciona a mi idea',
   87,
   'Creates a concrete reason to return without a noisy social feed.',
   'Crea un motivo concreto para volver sin convertirlo en un feed ruidoso.'),
  ('fanrank',
   'Merge duplicate ideas without losing their supporters',
   'Fusionar ideas duplicadas sin perder a quienes las apoyaron',
   82,
   'Concentrates demand and stops wording variants from splitting the ranking.',
   'Concentra la demanda y evita que distintas redacciones dividan el ranking.'),
  ('fanrank',
   'Follow a profile without creating an account',
   'Seguir un perfil sin crear una cuenta',
   77,
   'A low-friction return loop fits a public board better than forced signup.',
   'Un retorno sin fricción encaja mejor en un tablón público que obligar a registrarse.'),
  ('fanrank',
   'Accessible voting with keyboard and screen-reader status',
   'Votación accesible con teclado y estado para lector de pantalla',
   76,
   'Every supporter should be able to understand and change their vote.',
   'Toda persona debe poder entender y cambiar su apoyo.'),
  ('fanrank',
   'Export the final Top 3 as a transparent share card',
   'Exportar el Top 3 final como tarjeta compartible y transparente',
   74,
   'Turns the result into distribution while preserving the visible ranking source.',
   'Convierte el resultado en distribución conservando la fuente visible del ranking.'),

  -- Rubius: 3 existentes + 7 = 10.
  ('rubius',
   'A yearly Minecraft series with a clear ending',
   'Una serie anual de Minecraft con un final claro',
   83,
   'A finite season keeps the nostalgia while avoiding an endless commitment.',
   'Una temporada finita conserva la nostalgia sin exigir un compromiso infinito.'),
  ('rubius',
   'React to fan-made animations in one dedicated video',
   'Reaccionar a animaciones de fans en un vídeo dedicado',
   78,
   'Rewards community creativity and produces a format fans can feed directly.',
   'Premia la creatividad de la comunidad y crea un formato que los fans pueden alimentar.'),
  ('rubius',
   'One retro-game challenge chosen by fans each month',
   'Un reto mensual de juego retro elegido por los fans',
   76,
   'Combines audience choice with a compact and repeatable recording format.',
   'Une elección de la audiencia con un formato breve y repetible.'),
  ('rubius',
   'A calm podcast episode about the early YouTube years',
   'Un podcast tranquilo sobre los primeros años de YouTube',
   75,
   'The archive and lessons have value beyond a one-off reaction video.',
   'El archivo y sus aprendizajes valen más que una reacción puntual.'),
  ('rubius',
   'Publish the unused clips from major series as a blooper reel',
   'Publicar las tomas descartadas de grandes series como vídeo de fallos',
   72,
   'Reuses material fans already care about with little new production.',
   'Reutiliza material que ya interesa con poca producción nueva.'),
  ('rubius',
   'A community art challenge with the winner credited on screen',
   'Un reto de arte de la comunidad con crédito en pantalla para quien gane',
   70,
   'Recognition makes participation meaningful without promising money or access.',
   'El reconocimiento da sentido a participar sin prometer dinero ni acceso.'),
  ('rubius',
   'Spanish subtitles on archive videos with the most international views',
   'Subtítulos revisados en los vídeos antiguos con más audiencia internacional',
   68,
   'Improves the long-tail catalogue instead of relying only on new uploads.',
   'Mejora el catálogo a largo plazo sin depender solo de nuevos vídeos.'),

  -- Ibai: 3 existentes + 7 = 10.
  ('ibai',
   'Publish full event schedules in one mobile-friendly page',
   'Publicar los horarios completos de cada evento en una página cómoda para móvil',
   84,
   'Viewers miss less and support teams can point everyone to one source.',
   'La audiencia se pierde menos y el equipo dispone de una fuente única.'),
  ('ibai',
   'A transparent fan vote for one exhibition match',
   'Una votación transparente de fans para un combate de exhibición',
   80,
   'Gives the audience one bounded decision without handing over event safety.',
   'Da a la audiencia una decisión acotada sin ceder la seguridad del evento.'),
  ('ibai',
   'Release short documentaries about how large events are produced',
   'Publicar mini documentales sobre cómo se producen los grandes eventos',
   78,
   'The unseen production story extends the life of expensive events.',
   'La producción invisible alarga la vida de eventos costosos.'),
  ('ibai',
   'A public accessibility checklist for every arena event',
   'Un checklist público de accesibilidad para cada evento en recinto',
   77,
   'Attendees can decide early whether seating, audio and access meet their needs.',
   'Los asistentes pueden saber antes si asiento, audio y acceso cubren sus necesidades.'),
  ('ibai',
   'Give amateur commentators one supervised segment',
   'Dar a comentaristas amateurs un segmento supervisado',
   73,
   'Creates a visible path for new talent without risking the full broadcast.',
   'Crea una vía visible para talento nuevo sin arriesgar toda la retransmisión.'),
  ('ibai',
   'Publish corrected chapters for long interviews within 24 hours',
   'Publicar capítulos corregidos de las entrevistas largas en 24 horas',
   71,
   'Makes long conversations searchable and useful after the live moment.',
   'Hace que las conversaciones largas sean buscables y útiles después del directo.'),
  ('ibai',
   'Reserve a small ticket allocation for local community raffles',
   'Reservar una pequeña parte de entradas para sorteos de la comunidad local',
   69,
   'Adds local participation while keeping the main ticket system intact.',
   'Añade participación local sin alterar el sistema principal de entradas.'),

  -- Roblox: 3 existentes + 7 = 10.
  ('roblox',
   'Explain moderation decisions with an appeal timeline',
   'Explicar cada decisión de moderación con un plazo de apelación',
   84,
   'Clear reasons and deadlines reduce arbitrary-feeling account losses.',
   'Motivos y plazos claros reducen la sensación de perder una cuenta arbitrariamente.'),
  ('roblox',
   'Performance labels before joining an experience',
   'Etiquetas de rendimiento antes de entrar en una experiencia',
   79,
   'Players on modest devices can avoid experiences their hardware cannot run.',
   'Quien usa un dispositivo modesto puede evitar experiencias que no funcionarán bien.'),
  ('roblox',
   'A discovery tab for small quality games without paid placement',
   'Una pestaña para descubrir juegos pequeños de calidad sin pagar posición',
   78,
   'Reduces dependence on advertising and broadens the creator pipeline.',
   'Reduce la dependencia de anuncios y amplía la cantera de creadores.'),
  ('roblox',
   'Session and spending limits children can understand',
   'Límites de sesión y gasto que los menores puedan entender',
   77,
   'Visible limits work better when the child and the parent see the same rule.',
   'Los límites funcionan mejor si menor y familia ven la misma regla.'),
  ('roblox',
   'Version history and rollback for published experiences',
   'Historial de versiones y restauración para experiencias publicadas',
   75,
   'A safe rollback protects creator work when an update breaks production.',
   'Una restauración segura protege el trabajo cuando una actualización rompe producción.'),
  ('roblox',
   'Verified age-range labels written in plain language',
   'Etiquetas verificadas de edad escritas en lenguaje claro',
   73,
   'Families need more than a generic rating to judge specific experiences.',
   'Las familias necesitan más que una nota genérica para valorar cada experiencia.'),
  ('roblox',
   'Built-in accessibility checks in Roblox Studio',
   'Comprobaciones de accesibilidad integradas en Roblox Studio',
   72,
   'Early checks make captions, contrast and controls cheaper to fix.',
   'Detectarlo pronto abarata corregir subtítulos, contraste y controles.'),

  -- Discord: 3 existentes + 7 = 10.
  ('discord',
   'Export a server knowledge archive with permissions preserved',
   'Exportar el conocimiento de un servidor conservando los permisos',
   82,
   'Communities need a controlled backup without exposing private channels.',
   'Las comunidades necesitan copia controlada sin exponer canales privados.'),
  ('discord',
   'Automatic transcripts for opted-in stage events',
   'Transcripciones automáticas para eventos de escenario que lo activen',
   80,
   'Makes live knowledge searchable and accessible after the event.',
   'Hace el conocimiento del directo buscable y accesible después.'),
  ('discord',
   'Per-thread notification controls that inherit sensible defaults',
   'Controles de notificación por hilo con valores heredados sensatos',
   78,
   'Users can follow one discussion without muting or enabling a whole channel.',
   'Permite seguir una conversación sin silenciar ni activar todo el canal.'),
  ('discord',
   'A moderation queue with evidence visible to reviewers',
   'Una cola de moderación con la evidencia visible para quien revisa',
   77,
   'Consistent decisions are easier when context travels with the report.',
   'Es más fácil decidir con coherencia si el contexto acompaña al reporte.'),
  ('discord',
   'Forum tags that server members can combine in search',
   'Etiquetas de foro combinables por los miembros al buscar',
   74,
   'Structured filtering turns busy forums into reusable knowledge bases.',
   'El filtrado estructurado convierte foros activos en conocimiento reutilizable.'),
  ('discord',
   'Low-bandwidth voice mode with a visible quality tradeoff',
   'Modo de voz de bajo consumo con la pérdida de calidad visible',
   72,
   'Keeps communities reachable on weak connections without hidden degradation.',
   'Mantiene comunidades accesibles con mala conexión sin degradación oculta.'),
  ('discord',
   'Shared screen-reader labels for custom role icons',
   'Etiquetas para lector de pantalla en los iconos personalizados de roles',
   69,
   'Custom visuals should not erase status information for blind members.',
   'Los elementos visuales no deben borrar información para miembros ciegos.'),

  -- X / Twitter: 3 existentes + 7 = 10.
  ('x-twitter',
   'Search and folders inside bookmarks',
   'Buscador y carpetas dentro de los marcadores',
   84,
   'Saved posts become useful only when people can retrieve them.',
   'Los posts guardados solo sirven si luego se pueden recuperar.'),
  ('x-twitter',
   'Let users hide verified spam from their replies',
   'Permitir ocultar spam verificado de las respuestas',
   82,
   'Payment status should never outrank conversation quality controls.',
   'Pagar no debe estar por encima del control de calidad de una conversación.'),
  ('x-twitter',
   'Show a complete edit history on edited public posts',
   'Mostrar el historial completo de edición de los posts públicos',
   80,
   'Transparency preserves accountability while still allowing typo fixes.',
   'La transparencia conserva responsabilidad y permite corregir erratas.'),
  ('x-twitter',
   'One switch to disable autoplay and high-data media',
   'Un interruptor para desactivar autoplay y multimedia de alto consumo',
   76,
   'Users on limited data need a predictable lightweight timeline.',
   'Quien tiene datos limitados necesita una cronología ligera y predecible.'),
  ('x-twitter',
   'Community Notes status visible before reposting',
   'Estado de Community Notes visible antes de repostear',
   75,
   'A warning before amplification is more useful than correction afterward.',
   'Avisar antes de amplificar sirve más que corregir después.'),
  ('x-twitter',
   'Lists with duplicate detection and bulk cleanup',
   'Listas con detección de duplicados y limpieza en bloque',
   70,
   'Long-lived lists decay and need maintenance tools, not manual hunting.',
   'Las listas antiguas se degradan y necesitan mantenimiento, no búsqueda manual.'),
  ('x-twitter',
   'Plain-language explanations for reach restrictions',
   'Explicaciones claras cuando se limita el alcance',
   69,
   'Creators can correct behavior only when the rule and evidence are visible.',
   'Los creadores solo pueden corregir si ven la regla y la evidencia.'),

  -- ChatGPT: 3 existentes + 7 = 10.
  ('chatgpt',
   'A visible usage meter with exact reset times',
   'Un medidor de uso visible con la hora exacta de reinicio',
   86,
   'Predictable capacity lets people choose the right task before starting.',
   'Saber la capacidad permite elegir la tarea correcta antes de empezar.'),
  ('chatgpt',
   'Branch a conversation without copying the whole chat',
   'Ramificar una conversación sin copiar todo el chat',
   82,
   'Alternative paths become testable without destroying the useful history.',
   'Permite probar caminos alternativos sin destruir el historial útil.'),
  ('chatgpt',
   'Project export with files, instructions and chat links intact',
   'Exportar un proyecto conservando archivos, instrucciones y enlaces a chats',
   80,
   'Portable context prevents lock-in and makes backups verifiable.',
   'El contexto portable evita dependencia y permite verificar copias.'),
  ('chatgpt',
   'Version history for edited project instructions',
   'Historial de versiones para instrucciones de proyecto editadas',
   77,
   'A rollback makes high-impact instruction changes safe to test.',
   'Poder volver atrás hace seguras las pruebas con instrucciones críticas.'),
  ('chatgpt',
   'A citations-only research mode with unsupported claims flagged',
   'Un modo de investigación con citas y avisos en afirmaciones sin apoyo',
   76,
   'The mode makes evidence quality visible instead of merely requesting sources.',
   'Hace visible la calidad de evidencia en vez de limitarse a pedir fuentes.'),
  ('chatgpt',
   'Per-project notification controls for completed tasks',
   'Controles de aviso por proyecto para tareas terminadas',
   72,
   'Users can follow long work without receiving unrelated noise.',
   'Permite seguir trabajos largos sin recibir ruido de otros proyectos.'),
  ('chatgpt',
   'A privacy preview before sharing a conversation link',
   'Una vista previa de privacidad antes de compartir un chat',
   71,
   'A final review catches names, files and hidden context before publication.',
   'Una revisión final detecta nombres, archivos y contexto antes de publicar.'),

  -- Claude: 3 existentes + 7 = 10.
  ('claude',
   'Branch a chat while preserving the shared context',
   'Ramificar un chat conservando el contexto compartido',
   82,
   'Users can compare approaches without duplicating a long setup.',
   'Permite comparar enfoques sin duplicar una preparación larga.'),
  ('claude',
   'Project export with artifacts and citations preserved',
   'Exportar proyectos conservando artefactos y citas',
   80,
   'A complete archive makes professional work portable and auditable.',
   'Un archivo completo hace el trabajo profesional portable y auditable.'),
  ('claude',
   'Notify me when a usage window is available again',
   'Avísame cuando vuelva a estar disponible la ventana de uso',
   79,
   'A single reset alert turns waiting into a clear return point.',
   'Un solo aviso de reinicio convierte la espera en un retorno claro.'),
  ('claude',
   'Source support indicators on factual paragraphs',
   'Indicadores de respaldo de fuentes en párrafos factuales',
   77,
   'Readers can separate cited evidence from model inference at a glance.',
   'Permite separar de un vistazo evidencia citada e inferencia del modelo.'),
  ('claude',
   'Version history for project knowledge files',
   'Historial de versiones para archivos de conocimiento del proyecto',
   75,
   'Rollback protects a shared context base from accidental replacement.',
   'Volver atrás protege el contexto compartido de reemplazos accidentales.'),
  ('claude',
   'Granular permissions when sharing an artifact',
   'Permisos granulares al compartir un artefacto',
   72,
   'View, comment and edit access should not be one undifferentiated link.',
   'Ver, comentar y editar no deberían depender del mismo enlace.'),
  ('claude',
   'An offline draft queue that sends when connection returns',
   'Una cola de borradores sin conexión que envíe al volver internet',
   69,
   'Protects composed work without pretending the model itself runs offline.',
   'Protege lo escrito sin fingir que el modelo funciona sin conexión.'),

  -- Minecraft: 3 existentes + 7 = 10.
  ('minecraft',
   'More biome identity through unique ambient sounds and weather',
   'Más identidad para cada bioma con sonidos y clima propios',
   79,
   'Atmosphere adds exploration value without requiring a new progression system.',
   'La atmósfera añade exploración sin exigir otro sistema de progreso.'),
  ('minecraft',
   'A built-in map marker system shared with a server team',
   'Un sistema de marcadores de mapa compartido con el equipo del servidor',
   78,
   'Coordinates are functional but poor for collaborative exploration.',
   'Las coordenadas funcionan, pero son torpes para explorar en grupo.'),
  ('minecraft',
   'Reliable performance mode for large redstone worlds',
   'Un modo de rendimiento fiable para mundos grandes de redstone',
   77,
   'Technical builders need predictable simulation more than visual effects.',
   'Los constructores técnicos necesitan simulación predecible más que efectos.'),
  ('minecraft',
   'Pet safety controls: stay home, follow and avoid hazards',
   'Controles de seguridad para mascotas: casa, seguir y evitar peligros',
   75,
   'Long-lived companions should not be lost to basic pathfinding mistakes.',
   'Las mascotas no deberían perderse por errores básicos de ruta.'),
  ('minecraft',
   'World-level accessibility presets for flashes and camera movement',
   'Presets de accesibilidad por mundo para destellos y movimiento de cámara',
   73,
   'Shared presets make multiplayer safer without repeated manual setup.',
   'Los presets compartidos hacen el multijugador más seguro sin repetir ajustes.'),
  ('minecraft',
   'Official server backup rotation with one-click restore',
   'Copias rotatorias oficiales de servidor con restauración en un toque',
   72,
   'Recovery should be routine before an update or griefing incident.',
   'Recuperarse debe ser rutinario antes de una actualización o sabotaje.'),
  ('minecraft',
   'A clearer in-game guide to redstone components',
   'Una guía dentro del juego más clara para componentes de redstone',
   69,
   'New players should learn core behavior without leaving the game.',
   'Quien empieza debería aprender el comportamiento básico sin salir del juego.'),

  -- Fortnite: 3 existentes + 7 = 10.
  ('fortnite',
   'A permanent low-spec playlist with stable performance targets',
   'Una lista permanente para equipos modestos con rendimiento estable',
   80,
   'A stable target keeps more players in matches after visual updates.',
   'Un objetivo estable mantiene jugadores tras las actualizaciones visuales.'),
  ('fortnite',
   'Search Creative maps by session length and party size',
   'Buscar mapas de Creativo por duración y tamaño del grupo',
   78,
   'Players choose better when discovery reflects the time and friends available.',
   'Se elige mejor si el descubrimiento refleja tiempo y amigos disponibles.'),
  ('fortnite',
   'A locker archive for cosmetics you never use',
   'Un archivo del armario para cosméticos que nunca usas',
   76,
   'Large collections need organization without deleting purchased items.',
   'Las colecciones grandes necesitan orden sin borrar compras.'),
  ('fortnite',
   'Explain anti-cheat penalties and provide an appeal receipt',
   'Explicar las sanciones antitrampas y dar justificante de apelación',
   75,
   'Clear evidence and a traceable appeal improve trust in enforcement.',
   'Evidencia clara y apelación trazable mejoran la confianza.'),
  ('fortnite',
   'Team color and effect presets for color-blind players',
   'Presets de colores y efectos de equipo para daltonismo',
   73,
   'Combat information must not depend on one color distinction.',
   'La información de combate no debe depender de distinguir un solo color.'),
  ('fortnite',
   'Parental purchase approvals with item-level context',
   'Aprobación familiar de compras con contexto de cada objeto',
   71,
   'Families can approve a specific request instead of enabling open spending.',
   'La familia aprueba una petición concreta sin abrir todo el gasto.'),
  ('fortnite',
   'Publish Creative map update notes inside favorites',
   'Mostrar las novedades de mapas de Creativo dentro de favoritos',
   69,
   'Returning players can see why a saved island is worth reopening.',
   'Quien vuelve ve por qué merece reabrir una isla guardada.'),

  -- YouTube: 3 existentes + 7 = 10.
  ('youtube',
   'Let viewers disable Shorts per channel',
   'Permitir desactivar Shorts por canal',
   83,
   'Subscribers may want long videos from a creator without the short feed.',
   'Un suscriptor puede querer vídeos largos sin recibir el feed corto.'),
  ('youtube',
   'Search spoken words across your watch history',
   'Buscar palabras habladas dentro del historial',
   82,
   'People often remember a phrase but not the video title.',
   'A menudo se recuerda una frase, no el título del vídeo.'),
  ('youtube',
   'A subscriptions feed with no recommendations mixed in',
   'Un feed de suscripciones sin recomendaciones mezcladas',
   80,
   'Following a channel should offer one predictable complete view.',
   'Seguir un canal debe dar una vista completa y predecible.'),
  ('youtube',
   'Bulk repair tools for old playlists',
   'Herramientas en bloque para reparar playlists antiguas',
   77,
   'Duplicates, unavailable videos and wrong order are painful one by one.',
   'Duplicados, vídeos caídos y orden incorrecto son dolorosos uno por uno.'),
  ('youtube',
   'Creator-set chapter corrections after publishing',
   'Correcciones de capítulos por el creador después de publicar',
   74,
   'Accurate chapters improve search and accessibility over a long lifetime.',
   'Capítulos precisos mejoran búsqueda y accesibilidad durante años.'),
  ('youtube',
   'A visible sponsor disclosure field linked to the segment',
   'Un campo visible de patrocinio enlazado al segmento',
   72,
   'Structured disclosure is clearer than relying on description text alone.',
   'Una marca estructurada es más clara que depender solo de la descripción.'),
  ('youtube',
   'Default caption style saved across every device',
   'Guardar el estilo de subtítulos en todos los dispositivos',
   70,
   'Accessibility preferences should follow the viewer, not the television.',
   'La accesibilidad debe seguir a la persona, no al televisor.'),

  -- TikTok: 3 existentes + 7 = 10.
  ('tiktok',
   'Searchable watch history with date filters',
   'Historial buscable con filtros por fecha',
   82,
   'A video seen once should not become impossible to recover.',
   'Un vídeo visto una vez no debería ser imposible de recuperar.'),
  ('tiktok',
   'Creator comment filters that show why a reply was held',
   'Filtros de comentarios que expliquen por qué se retuvo una respuesta',
   78,
   'Transparent moderation reduces both abuse and accidental censorship.',
   'La moderación transparente reduce abuso y censura accidental.'),
  ('tiktok',
   'Source links attached to educational claims',
   'Enlaces de fuente unidos a afirmaciones educativas',
   76,
   'Checkable context makes useful short videos safer to share.',
   'El contexto comprobable hace más seguro compartir vídeos útiles.'),
  ('tiktok',
   'Caption quality warnings before publishing',
   'Avisos de calidad de subtítulos antes de publicar',
   75,
   'Creators can fix missing speech or timing before viewers encounter it.',
   'Permite corregir voz omitida o tiempos antes de que lo vea la audiencia.'),
  ('tiktok',
   'Screen-time breaks that cannot be dismissed by one accidental tap',
   'Pausas de tiempo de uso que no se descarten con un toque accidental',
   73,
   'A deliberate pause is more honest than a decorative warning.',
   'Una pausa deliberada es más honesta que un aviso decorativo.'),
  ('tiktok',
   'Per-video download and reuse permissions in plain language',
   'Permisos claros de descarga y reutilización en cada vídeo',
   71,
   'Creators and viewers need to know what saving permits before reuse.',
   'Creadores y audiencia deben saber qué permite guardar antes de reutilizar.'),
  ('tiktok',
   'Family controls with a shared activity summary, not message contents',
   'Controles familiares con resumen de actividad, no contenido de mensajes',
   69,
   'Safety oversight can preserve privacy when it focuses on patterns.',
   'La supervisión puede preservar privacidad si se centra en patrones.'),

  -- Instagram: 3 existentes + 7 = 10.
  ('instagram',
   'Search inside saved collections',
   'Buscar dentro de las colecciones guardadas',
   82,
   'Collections become archives only when old posts are retrievable.',
   'Las colecciones solo son archivo si se recuperan posts antiguos.'),
  ('instagram',
   'A follower-only feed with no suggested posts',
   'Un feed solo de cuentas seguidas y sin sugerencias',
   81,
   'One stable view restores the core promise of following people.',
   'Una vista estable recupera la promesa básica de seguir personas.'),
  ('instagram',
   'Bulk controls for abusive comment patterns',
   'Controles en bloque para patrones de comentarios abusivos',
   78,
   'Creators need pattern tools instead of deleting attacks one at a time.',
   'Los creadores necesitan patrones, no borrar ataques uno por uno.'),
  ('instagram',
   'Alt-text prompts and preview before posting',
   'Aviso y vista previa del texto alternativo antes de publicar',
   76,
   'A small publishing check improves access for every future viewer.',
   'Una comprobación pequeña mejora el acceso de toda audiencia futura.'),
  ('instagram',
   'A real tablet layout for feed and messages',
   'Un diseño real para tablet en feed y mensajes',
   73,
   'Large screens should provide more context rather than a stretched phone.',
   'Una pantalla grande debe dar contexto, no estirar el móvil.'),
  ('instagram',
   'Show edit history for captions on public posts',
   'Mostrar el historial de edición de textos en posts públicos',
   71,
   'Public changes stay accountable without banning useful corrections.',
   'Los cambios públicos conservan responsabilidad sin prohibir correcciones.'),
  ('instagram',
   'Per-account controls for story and reel autoplay',
   'Controles por cuenta para autoplay de stories y reels',
   69,
   'Users can reduce noise selectively instead of muting people entirely.',
   'Permite reducir ruido sin silenciar por completo a una persona.'),

  -- Spotify: 3 existentes + 7 = 10.
  ('spotify',
   'Cross-device queue that never silently replaces itself',
   'Una cola entre dispositivos que nunca se reemplace en silencio',
   83,
   'The queue is session state and should survive moving from phone to desktop.',
   'La cola es estado de sesión y debe sobrevivir al cambio de dispositivo.'),
  ('spotify',
   'Separate music and podcast recommendations completely',
   'Separar por completo recomendaciones de música y podcasts',
   80,
   'Different listening intents should not compete in one home surface.',
   'Intenciones distintas no deberían competir en la misma portada.'),
  ('spotify',
   'Granular permissions for collaborative playlists',
   'Permisos granulares en playlists colaborativas',
   78,
   'Owners need invite, add, reorder and delete controls to prevent vandalism.',
   'Se necesitan permisos para invitar, añadir, ordenar y borrar sin sabotaje.'),
  ('spotify',
   'Complete songwriter and performer credits on every track',
   'Créditos completos de composición e interpretación en cada canción',
   77,
   'Reliable credits reward contributors and improve music discovery.',
   'Créditos fiables reconocen a colaboradores y mejoran el descubrimiento.'),
  ('spotify',
   'Library export in an open, documented format',
   'Exportar la biblioteca en un formato abierto y documentado',
   75,
   'A verifiable backup protects years of curation without copying audio.',
   'Una copia verificable protege años de selección sin copiar audio.'),
  ('spotify',
   'A permanent off switch for Smart Shuffle per playlist',
   'Un apagado permanente de Smart Shuffle por playlist',
   73,
   'A curated order should remain the listener choice until changed.',
   'El orden elegido debe seguir así hasta que el oyente lo cambie.'),
  ('spotify',
   'Listening history search by date, device and context',
   'Buscar historial por fecha, dispositivo y contexto',
   71,
   'Recovering one forgotten track should not require scrolling for hours.',
   'Recuperar una canción olvidada no debería exigir horas de scroll.'),

  -- Twitch: 3 existentes + 7 = 10.
  ('twitch',
   'Search spoken moments inside VODs',
   'Buscar momentos hablados dentro de las VOD',
   82,
   'Long broadcasts become useful archives when moments are findable.',
   'Los directos largos se vuelven archivo útil si se encuentran momentos.'),
  ('twitch',
   'A shared moderator queue with decision notes',
   'Una cola compartida de moderación con notas de decisión',
   79,
   'Context and notes make enforcement consistent across a rotating team.',
   'Contexto y notas hacen coherente la moderación entre turnos.'),
  ('twitch',
   'Caption quality and language labels before opening a stream',
   'Etiquetas de idioma y calidad de subtítulos antes de abrir un directo',
   77,
   'Viewers can choose accessible streams without trial and error.',
   'La audiencia puede elegir directos accesibles sin ensayo y error.'),
  ('twitch',
   'Discovery filters for language, stream size and session type',
   'Filtros de descubrimiento por idioma, tamaño y tipo de sesión',
   76,
   'Better intent filters give small relevant channels a fair route to viewers.',
   'Mejores filtros dan a canales pequeños una ruta justa a su audiencia.'),
  ('twitch',
   'A stable low-latency mode with visible tradeoffs',
   'Un modo estable de baja latencia con sus costes visibles',
   74,
   'Interactive communities can choose latency without hidden buffering costs.',
   'Las comunidades interactivas pueden elegir latencia sin costes ocultos.'),
  ('twitch',
   'Per-channel mobile data and autoplay controls',
   'Controles por canal de datos móviles y autoplay',
   71,
   'Viewers can keep selected channels lightweight without a global compromise.',
   'Permite aligerar canales concretos sin un compromiso global.'),
  ('twitch',
   'Clearer payout breakdown by subscription, ads and promotions',
   'Desglose más claro de pagos por suscripciones, anuncios y promociones',
   70,
   'Creators make better decisions when revenue sources are traceable.',
   'Los creadores deciden mejor si cada fuente de ingresos es trazable.'),

  -- Cuaderno MADRE: 5 existentes + 5 = 10.
  ('cuaderno-madre',
   'Export a complete notebook as readable HTML and JSON',
   'Exportar el cuaderno completo como HTML legible y JSON',
   83,
   'A human-readable copy and a structured copy protect different futures.',
   'Una copia legible y otra estructurada protegen futuros distintos.'),
  ('cuaderno-madre',
   'Offline capture queue that syncs without duplicate notes',
   'Cola de captura sin conexión que sincronice sin duplicados',
   80,
   'Capture must survive weak connectivity without creating cleanup work.',
   'La captura debe sobrevivir a mala conexión sin crear trabajo de limpieza.'),
  ('cuaderno-madre',
   'Version history with one-click restore for every page',
   'Historial de versiones y restauración en un toque para cada página',
   78,
   'Reversible editing makes experimentation safe on valuable notes.',
   'Editar de forma reversible hace seguras las pruebas sobre notas valiosas.'),
  ('cuaderno-madre',
   'Weekly resurfacing of one forgotten note with its original context',
   'Recuperar cada semana una nota olvidada con su contexto original',
   75,
   'Old knowledge creates value only when it returns at a useful moment.',
   'El conocimiento antiguo solo vale si regresa en un momento útil.'),
  ('cuaderno-madre',
   'Filter the link graph by topic, date and evidence status',
   'Filtrar el grafo de enlaces por tema, fecha y estado de evidencia',
   72,
   'Filters turn a beautiful graph into a decision tool.',
   'Los filtros convierten un grafo bonito en herramienta de decisión.')
) as v(section, title, title_es, ai_score, ai_reason, ai_reason_es)
where not exists (
  select 1
  from public.fr_ideas as existing
  where existing.section = v.section
    and existing.title = v.title
);

do $$
declare
  v_short text;
begin
  select string_agg(section || ':' || idea_count::text, ', ' order by section)
  into v_short
  from (
    select section, count(*)::int as idea_count
    from public.fr_ideas
    where approved = true
    group by section
    having count(*) < 10
  ) as short_profiles;

  if v_short is not null then
    raise exception 'FanRank v20 dejó perfiles bajo el mínimo de 10: %', v_short;
  end if;
end
$$;
