begin;

-- FanRank v8: qualified Pro pilot demand without pretending that billing exists.
-- Pricing is tied to feedback volume. Payment can never alter organic ranking.

alter table public.fr_promotion_requests
  drop constraint if exists fr_promotion_requests_placement_check;
alter table public.fr_promotion_requests
  add constraint fr_promotion_requests_profile_only_check
  check (placement = 'profile' and idea_id is null);

comment on constraint fr_promotion_requests_profile_only_check on public.fr_promotion_requests is
  'Paid distribution cannot target an individual idea because extra impressions could buy organic votes indirectly.';

create table public.fr_pro_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  section text references public.fr_sections(slug) on delete set null,
  organization_name text not null check (char_length(btrim(organization_name)) between 2 and 120),
  plan text not null check (plan in ('signal', 'decision', 'portfolio')),
  feedback_band text not null check (feedback_band in ('under_1000', '1000_5000', '5000_20000', 'over_20000')),
  cadence text not null check (cadence in ('monthly', 'weekly', 'daily')),
  goal text not null check (char_length(btrim(goal)) between 15 and 1200),
  status text not null default 'interested' check (status in ('interested', 'qualified', 'pilot_offered', 'accepted', 'declined')),
  pricing_version text not null default '2026-07-pilot',
  organic_rank_unchanged boolean not null default true check (organic_rank_unchanged = true),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index fr_pro_requests_user_created_idx
  on public.fr_pro_requests (user_id, created_at desc);
create index fr_pro_requests_section_created_idx
  on public.fr_pro_requests (section, created_at desc)
  where section is not null;
create index fr_pro_requests_status_created_idx
  on public.fr_pro_requests (status, created_at desc);

alter table public.fr_pro_requests enable row level security;

create policy fr_pro_requests_self_or_admin_read on public.fr_pro_requests
  for select to authenticated
  using (
    user_id = (select auth.uid())
    or exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );

revoke all on public.fr_pro_requests from public, anon, authenticated;
grant select (
  id, section, organization_name, plan, feedback_band, cadence, goal,
  status, pricing_version, organic_rank_unchanged, created_at, updated_at
) on public.fr_pro_requests to authenticated;

create or replace function public.fr_request_pro_pilot(
  p_section text,
  p_organization text,
  p_plan text,
  p_feedback_band text,
  p_cadence text,
  p_goal text
)
returns table(request_id bigint, request_status text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_section text := nullif(pg_catalog.btrim(p_section), '');
  v_organization text := pg_catalog.btrim(p_organization);
  v_goal text := pg_catalog.btrim(p_goal);
begin
  if v_actor is null then
    raise exception using errcode = '28000', message = 'Authentication required';
  end if;
  if v_organization is null or pg_catalog.char_length(v_organization) not between 2 and 120 then
    raise exception using errcode = '22023', message = 'Organization name required';
  end if;
  if p_plan is null or p_plan not in ('signal', 'decision', 'portfolio') then
    raise exception using errcode = '22023', message = 'Invalid plan';
  end if;
  if p_feedback_band is null or p_feedback_band not in ('under_1000', '1000_5000', '5000_20000', 'over_20000') then
    raise exception using errcode = '22023', message = 'Invalid feedback band';
  end if;
  if p_cadence is null or p_cadence not in ('monthly', 'weekly', 'daily') then
    raise exception using errcode = '22023', message = 'Invalid cadence';
  end if;
  if v_goal is null or pg_catalog.char_length(v_goal) not between 15 and 1200 then
    raise exception using errcode = '22023', message = 'Decision goal required';
  end if;
  if v_section is not null and not exists (
    select 1 from public.fr_sections s where s.slug = v_section
  ) then
    raise exception using errcode = '22023', message = 'Profile not found';
  end if;
  if (
    select pg_catalog.count(*) from public.fr_pro_requests r
    where r.user_id = v_actor and r.created_at >= current_timestamp - interval '24 hours'
  ) >= 3 then
    raise exception using errcode = 'P0001', message = 'Request limit reached';
  end if;

  return query
  insert into public.fr_pro_requests (
    user_id, section, organization_name, plan, feedback_band, cadence, goal
  ) values (
    v_actor, v_section, v_organization, p_plan, p_feedback_band, p_cadence, v_goal
  )
  returning id, status;
end;
$$;

revoke all on function public.fr_request_pro_pilot(text, text, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.fr_request_pro_pilot(text, text, text, text, text, text)
  to authenticated;

alter table public.fr_events
  drop constraint if exists fr_events_event_check;
alter table public.fr_events
  add constraint fr_events_event_check
  check (event in (
    'page_view', 'search', 'profile_open', 'idea_open', 'idea_share', 'vote', 'submission',
    'section_request', 'claim_request', 'suggest_open', 'similar_vote', 'auth_open',
    'auth_link_requested', 'auth_recovery_requested', 'auth_signed_in', 'auth_signed_out',
    'activity_open', 'team_interest', 'team_invite_created', 'owner_mode_open', 'owner_feedback',
    'owner_profile_request', 'profile_image_updated', 'promotion_interest', 'pro_interest'
  ));

comment on table public.fr_pro_requests is
  'Private demand-validation queue for a paid Pro pilot. It is not a subscription or payment record.';
comment on column public.fr_pro_requests.organic_rank_unchanged is
  'Hard trust boundary: buying analysis or delivery can never modify organic/AI ranking.';
comment on function public.fr_request_pro_pilot(text, text, text, text, text, text) is
  'Authenticated, rate-limited intake for Pro pilot interest; actor identity is derived server-side.';

commit;
