-- FanRank v17: directorio famoso (pedido de Tony 16-jul) + ideas semilla honestas.
-- Aplicada en producción el 2026-07-16 ~21:05 via Supabase MCP (apply_migration).
-- cuaderno-madre deja de tener prioridad (sigue buscable con la lupa).
update public.fr_sections set featured_rank = 900 where slug = 'cuaderno-madre';

insert into public.fr_sections
  (slug, name, emoji, kind, tagline, tagline_es, tags, featured_rank)
values
  ('minecraft', 'Minecraft', '⛏️', 'game',
   'Ideas for the blocky universe, ranked by usefulness and demand.',
   'Ideas para el universo de bloques, ordenadas por utilidad y demanda.',
   array['sandbox','mojang','multiplayer'], 11),
  ('fortnite', 'Fortnite', '🪂', 'game',
   'Community ideas for the island and beyond.',
   'Ideas de la comunidad para la isla y más allá.',
   array['battle-royale','epic-games','creative'], 12),
  ('youtube', 'YouTube', '▶️', 'social',
   'Ideas to make watching and creating better.',
   'Ideas para ver y crear mejor.',
   array['video','platform','creators'], 13),
  ('tiktok', 'TikTok', '🎵', 'social',
   'Suggestions for a smarter For You.',
   'Sugerencias para un For You más inteligente.',
   array['short-video','platform','fyp'], 14),
  ('instagram', 'Instagram', '📸', 'social',
   'Fan ideas for feed, stories and reels.',
   'Ideas de fans para el feed, las stories y los reels.',
   array['photos','reels','platform'], 15),
  ('spotify', 'Spotify', '🎧', 'company',
   'Listener ideas, ranked by demand.',
   'Ideas de oyentes ordenadas por demanda.',
   array['music','streaming','podcasts'], 16),
  ('twitch', 'Twitch', '🎮', 'social',
   'Viewer ideas for better live streams.',
   'Ideas de la audiencia para mejores directos.',
   array['streaming','live','creators'], 17)
on conflict (slug) do update
set name = excluded.name,
    emoji = excluded.emoji,
    kind = excluded.kind,
    tagline = excluded.tagline,
    tagline_es = excluded.tagline_es,
    tags = excluded.tags,
    featured_rank = excluded.featured_rank;

-- Ideas semilla: peticiones reales y conocidas de cada comunidad, presentadas como
-- contenido curado (sin votos falsos: web_votes=0, origin_upvotes=0, sin source_url falsa).
insert into public.fr_ideas
  (section, title, title_es, ai_score, ai_reason, ai_reason_es, approved, web_votes, origin_upvotes)
select v.section, v.title, v.title_es, v.ai_score, v.ai_reason, v.ai_reason_es, true, 0, 0
from (values
  ('fanrank', 'Owner status labels on ideas: seen, in review, done',
   'Etiquetas de estado del dueño en cada idea: vista, en revisión, hecha',
   84, 'Turns the board into a loop with answers; boards without replies die.',
   'Convierte el tablón en un ciclo con respuesta; los tablones sin respuesta mueren.'),
  ('fanrank', 'Public wall of implemented ideas with proof',
   'Muro público de ideas implementadas con su prueba',
   80, 'Shows the product listens; proof beats promises.',
   'Demuestra que se escucha; la evidencia vence a la promesa.'),
  ('fanrank', 'One-tap request for a missing profile',
   'Pedir en un toque un perfil que falta',
   74, 'Fans grow the directory exactly where demand already exists.',
   'Los fans amplían el directorio justo donde ya hay demanda.'),
  ('fanrank', 'Weekly digest of the top 3 ideas you follow',
   'Resumen semanal con el top 3 de lo que sigues',
   71, 'Cheap retention loop without notification spam.',
   'Retención barata sin spam de notificaciones.'),
  ('minecraft', 'Give the End dimension a full update',
   'Una actualización completa para el End',
   86, 'Most requested zone for years; huge replay value.',
   'La zona más pedida desde hace años; enorme rejugabilidad.'),
  ('minecraft', 'Real parity between Java and Bedrock',
   'Paridad real entre Java y Bedrock',
   82, 'Same game, same features; the split hurts every player.',
   'Mismo juego, mismas funciones; la división daña a todos.'),
  ('minecraft', 'A proper backpack to ease inventory pain',
   'Una mochila de verdad para aliviar el inventario',
   76, 'The oldest quality-of-life ask in the community.',
   'La mejora de comodidad más veterana de la comunidad.'),
  ('fortnite', 'First-person mode for Battle Royale',
   'Modo en primera persona para el Battle Royale',
   84, 'Reuses existing tech and refreshes the core mode.',
   'Reutiliza tecnología existente y refresca el modo principal.'),
  ('fortnite', 'Keep an OG map playlist always available',
   'Una lista con el mapa OG siempre disponible',
   79, 'OG seasons broke player records; demand is proven.',
   'Las temporadas OG batieron récords; la demanda está probada.'),
  ('fortnite', 'Gift skins straight from a friend''s wishlist',
   'Regalar skins directo desde la wishlist de un amigo',
   72, 'Wishlists already exist; gifting them prints goodwill.',
   'Las wishlists ya existen; regalarlas genera buena voluntad.'),
  ('youtube', 'Bring back the public dislike count',
   'Recuperar el contador público de dislikes',
   81, 'Restores a signal viewers used to avoid misleading content.',
   'Devuelve una señal que evitaba contenido engañoso.'),
  ('youtube', 'Playlists that auto-skip deleted or private videos',
   'Playlists que salten solas los vídeos borrados o privados',
   77, 'Removes a daily annoyance with zero downside.',
   'Elimina una molestia diaria sin ningún coste.'),
  ('youtube', 'Search inside a video''s comments',
   'Buscar dentro de los comentarios de un vídeo',
   73, 'Comments hold answers; finding them today is luck.',
   'Los comentarios guardan respuestas; hoy encontrarlas es suerte.'),
  ('tiktok', 'Make ''not interested'' actually learn',
   'Que ''no me interesa'' aprenda de verdad',
   83, 'Feed control is the top complaint among heavy users.',
   'El control del feed es la queja número uno de quien más lo usa.'),
  ('tiktok', 'Folders with search for saved videos',
   'Carpetas con buscador para los vídeos guardados',
   76, 'Saving is useless if you cannot find it again.',
   'Guardar no sirve si luego no lo encuentras.'),
  ('tiktok', 'Filter reposts and near-duplicates from the feed',
   'Filtrar reposts y vídeos casi duplicados del feed',
   74, 'Less deja vu means longer, happier sessions.',
   'Menos déjà vu, sesiones más largas y contentas.'),
  ('instagram', 'Chronological feed that stays as your default',
   'Feed cronológico que se quede como tu opción por defecto',
   84, 'The setting exists but resets; users keep asking for it to stick.',
   'La opción existe pero se resetea; la gente pide que se quede.'),
  ('instagram', 'A real control over how many suggested posts appear',
   'Un control real de cuántas sugerencias aparecen',
   78, 'Gives users agency without removing discovery.',
   'Da control sin eliminar el descubrimiento.'),
  ('instagram', 'Story drafts synced across devices',
   'Borradores de stories sincronizados entre dispositivos',
   72, 'Creators lose work daily; sync is table stakes elsewhere.',
   'Los creadores pierden trabajo a diario; sincronizar es lo mínimo.'),
  ('spotify', 'Ship lossless audio without a price hike',
   'Lanzar el audio sin pérdida sin subir el precio',
   85, 'Announced years ago; rivals already include it.',
   'Anunciado hace años; la competencia ya lo incluye.'),
  ('spotify', 'Friend activity on mobile',
   'Actividad de amigos también en el móvil',
   78, 'A beloved desktop social feature missing where users live.',
   'La función social querida del escritorio falta donde vive la gente.'),
  ('spotify', 'Playlist folders on mobile',
   'Carpetas de playlists en el móvil',
   74, 'Power users organize on desktop and lose it on the phone.',
   'Quien más organiza lo hace en escritorio y lo pierde en el móvil.'),
  ('twitch', 'Rewind the live stream without leaving it',
   'Rebobinar el directo sin salir de él',
   81, 'Missing a clutch moment forces a clunky VOD detour.',
   'Perderte un momentazo obliga a un rodeo incómodo por la VOD.'),
  ('twitch', 'A clip editor that includes chat replay',
   'Editor de clips que incluya la repetición del chat',
   79, 'Chat reactions are half the moment; clips lose them.',
   'La reacción del chat es la mitad del momento; los clips la pierden.'),
  ('twitch', 'Picture-in-picture on mobile for everyone',
   'PiP en el móvil para todo el mundo',
   73, 'Keeps streams running while people live their lives.',
   'Mantiene el directo mientras la gente vive su vida.')
) as v(section, title, title_es, ai_score, ai_reason, ai_reason_es)
where not exists (
  select 1 from public.fr_ideas i
  where i.section = v.section and i.title = v.title
);
