-- FanRank v18: cero perfiles vacíos — ideas semilla honestas para los 7 perfiles restantes
-- (rubius, ibai, roblox, discord, x-twitter, chatgpt, claude; 3 por perfil).
-- Aplicada en producción el 2026-07-16 ~21:45 via Supabase MCP (apply_migration,
-- nombre: fanrank_v18_seed_remaining_profiles). Mismo patrón de integridad que v17:
-- web_votes=0, origin_upvotes=0, sin source_url inventada; la nota IA es la única
-- jerarquía. Para personas reales: solo sugerencias de formato/contenido respetuosas.
-- El SQL completo (idéntico al aplicado) vive en el historial de migraciones de Supabase;
-- espejo local para el repo:
insert into public.fr_ideas
  (section, title, title_es, ai_score, ai_reason, ai_reason_es, approved, web_votes, origin_upvotes)
select v.section, v.title, v.title_es, v.ai_score, v.ai_reason, v.ai_reason_es, true, 0, 0
from (values
  ('rubius', 'Bring back long variety streams with community games',
   'Más directos largos de variedad con juegos junto a la comunidad',
   79, 'Low-cost format with high closeness; easy to pick up again.',
   'Formato barato y muy cercano; fácil de retomar cuando quiera.'),
  ('rubius', 'A monthly Q&A answering questions picked from this board',
   'Un Q&A mensual respondiendo preguntas elegidas de este tablón',
   74, 'Turns fan attention into a direct, low-effort format.',
   'Convierte la atención de los fans en un formato directo y de poco esfuerzo.'),
  ('rubius', 'Behind-the-scenes of how a video is actually made',
   'Un detrás de las cámaras de cómo se hace un vídeo de verdad',
   71, 'Evergreen content fans of any creator consistently enjoy.',
   'Contenido atemporal que los fans de cualquier creador disfrutan.'),
  ('ibai', 'Subtitle the big events in English for global fans',
   'Subtítulos en inglés para los grandes eventos',
   81, 'Multiplies the reach of events that already exist.',
   'Multiplica el alcance de eventos que ya existen.'),
  ('ibai', 'A fan-voted category in the yearly awards, chosen from this board',
   'Una categoría votada por fans en los premios anuales, elegida desde este tablón',
   76, 'Cheap to add and gives the audience real ownership.',
   'Barata de añadir y da a la audiencia protagonismo real.'),
  ('ibai', 'More grassroots sports events with amateur players',
   'Más eventos deportivos con gente amateur',
   72, 'Reuses a proven format that turns viewers into participants.',
   'Reutiliza un formato probado que convierte espectadores en participantes.'),
  ('roblox', 'Stronger kid safety moderation without killing creativity',
   'Mejor moderación para menores sin frenar la creatividad',
   85, 'Safety is the top concern for the youngest player base.',
   'La seguridad es la mayor preocupación con la base más joven.'),
  ('roblox', 'A fairer revenue share for small creators',
   'Un reparto de ingresos más justo para creadores pequeños',
   82, 'Creator economics decide the platform''s long-term content.',
   'La economía de los creadores decide el contenido a largo plazo.'),
  ('roblox', 'Native parental controls for voice chat',
   'Controles parentales nativos para el chat de voz',
   76, 'Removes a real adoption blocker for families.',
   'Elimina un freno real de adopción para las familias.'),
  ('discord', 'Search that actually finds things in threads and forums',
   'Búsqueda que encuentre de verdad en hilos y foros',
   82, 'Knowledge dies in unsearchable threads today.',
   'El conocimiento muere hoy en hilos donde nada se encuentra.'),
  ('discord', 'A lighter mobile app for older phones',
   'Una app móvil más ligera para móviles antiguos',
   77, 'Expands access where communities actually live.',
   'Amplía el acceso justo donde viven las comunidades.'),
  ('discord', 'One-tap notification presets per server',
   'Presets de notificaciones por servidor en un toque',
   74, 'Solves the most common setup pain in seconds.',
   'Resuelve en segundos el ajuste más pesado de configurar.'),
  ('x-twitter', 'Chronological following feed that stays as default',
   'El feed de seguidos cronológico como opción fija',
   82, 'Users keep asking for their choice to persist.',
   'La gente pide que su elección se mantenga entre sesiones.'),
  ('x-twitter', 'Real controls against bot replies',
   'Controles reales contra las respuestas de bots',
   80, 'Reply quality is the most visible daily experience.',
   'La calidad de las respuestas es la experiencia diaria más visible.'),
  ('x-twitter', 'A longer edit window that still prevents abuse',
   'Una ventana de edición más larga que siga evitando abusos',
   73, 'Fixes typos without rewriting history.',
   'Corrige erratas sin permitir reescribir la historia.'),
  ('chatgpt', 'Show sources by default when stating facts',
   'Mostrar fuentes por defecto al afirmar hechos',
   84, 'Trust grows when claims are checkable in one tap.',
   'La confianza crece cuando lo afirmado se comprueba en un toque.'),
  ('chatgpt', 'A simple family mode for kids',
   'Un modo familiar sencillo para menores',
   75, 'Opens safe use for a huge audience segment.',
   'Abre un uso seguro para un segmento enorme.'),
  ('chatgpt', 'Offline mode for basic tasks',
   'Modo sin conexión para tareas básicas',
   70, 'Keeps core value when connectivity fails.',
   'Mantiene el valor básico cuando falla la conexión.'),
  ('claude', 'Voice conversations in Spanish',
   'Conversaciones por voz en español',
   80, 'Voice is the most natural interface for many users.',
   'La voz es la interfaz más natural para muchísima gente.'),
  ('claude', 'A clear usage meter so limits never surprise you',
   'Un medidor de uso claro para que el límite nunca sorprenda',
   78, 'Predictability beats frustration mid-task.',
   'La previsibilidad evita la frustración a mitad de tarea.'),
  ('claude', 'Shared projects for small teams without setup',
   'Proyectos compartidos para equipos pequeños sin configuración',
   76, 'Collaboration is the next natural step after solo use.',
   'Colaborar es el paso natural después del uso individual.')
) as v(section, title, title_es, ai_score, ai_reason, ai_reason_es)
where not exists (
  select 1 from public.fr_ideas i
  where i.section = v.section and i.title = v.title
);
