begin;

-- FanRank v7: platform owner studio, accountable profile media and private visual feedback.
-- Bootstrap of a real owner is deliberately NOT committed here: it is performed once,
-- out-of-band, by matching a confirmed auth user and storing only that user's UUID.

alter table public.fr_sections
  add column image_path text,
  add column image_alt text,
  add column image_source_url text,
  add column image_credit text,
  add column image_rights text,
  add column image_updated_at timestamptz,
  add column image_updated_by uuid references auth.users(id) on delete set null;

alter table public.fr_sections
  add constraint fr_sections_image_path_check
    check (image_path is null or image_path ~ '^[a-z0-9-]+/[0-9a-f-]+/[0-9]+-[a-z0-9]+\.(jpg|png|webp)$'),
  add constraint fr_sections_image_alt_check
    check (image_alt is null or char_length(btrim(image_alt)) between 2 and 180),
  add constraint fr_sections_image_source_url_check
    check (image_source_url is null or char_length(image_source_url) <= 700),
  add constraint fr_sections_image_credit_check
    check (image_credit is null or char_length(image_credit) <= 240),
  add constraint fr_sections_image_rights_check
    check (image_rights is null or image_rights in ('official_press', 'licensed', 'public_domain', 'owner_upload', 'generated'));

comment on column public.fr_sections.image_source_url is
  'Original source or license page for the current profile image; never a Google Images result URL.';
comment on column public.fr_sections.image_rights is
  'Declared rights basis for the current profile image. Promotion does not imply endorsement.';

create table public.fr_platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'admin')),
  status text not null default 'active' check (status in ('active', 'revoked')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default current_timestamp,
  revoked_at timestamptz
);
alter table public.fr_platform_admins enable row level security;
create policy fr_platform_admins_self_read on public.fr_platform_admins
  for select to authenticated
  using (user_id = (select auth.uid()));
revoke all on public.fr_platform_admins from anon, authenticated;
grant select (user_id, role, status, created_at) on public.fr_platform_admins to authenticated;

create table public.fr_owner_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page_path text not null check (char_length(page_path) between 1 and 500),
  zone text not null check (zone ~ '^[a-z0-9_-]{2,80}$'),
  message text not null check (char_length(btrim(message)) between 3 and 2000),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high')),
  screenshot_path text check (
    screenshot_path is null or
    screenshot_path ~ '^[0-9a-f-]+/[0-9]+-[a-z0-9]+\.(jpg|png|webp)$'
  ),
  status text not null default 'new' check (status in ('new', 'seen', 'planned', 'done', 'dismissed')),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);
alter table public.fr_owner_feedback enable row level security;
create policy fr_owner_feedback_admin_read on public.fr_owner_feedback
  for select to authenticated
  using (
    exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
create policy fr_owner_feedback_admin_insert on public.fr_owner_feedback
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
create policy fr_owner_feedback_admin_update on public.fr_owner_feedback
  for update to authenticated
  using (
    exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  )
  with check (
    exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
revoke all on public.fr_owner_feedback from anon, authenticated;
grant select (id, user_id, page_path, zone, message, priority, screenshot_path, status, created_at, updated_at)
  on public.fr_owner_feedback to authenticated;
grant insert (user_id, page_path, zone, message, priority, screenshot_path)
  on public.fr_owner_feedback to authenticated;
grant update (status, updated_at) on public.fr_owner_feedback to authenticated;
grant usage, select on sequence public.fr_owner_feedback_id_seq to authenticated;

create table public.fr_profile_requests (
  id bigint generated by default as identity primary key,
  requested_by uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 2 and 120),
  kind text not null check (kind in ('creator', 'company', 'game', 'social', 'ai', 'project')),
  notes text check (notes is null or char_length(notes) <= 1200),
  status text not null default 'pending' check (status in ('pending', 'researching', 'ready', 'published', 'rejected')),
  resolved_section text references public.fr_sections(slug) on delete set null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);
alter table public.fr_profile_requests enable row level security;
create policy fr_profile_requests_admin_read on public.fr_profile_requests
  for select to authenticated
  using (
    exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
create policy fr_profile_requests_admin_insert on public.fr_profile_requests
  for insert to authenticated
  with check (
    requested_by = (select auth.uid())
    and exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
create policy fr_profile_requests_admin_update on public.fr_profile_requests
  for update to authenticated
  using (
    exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  )
  with check (
    exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
revoke all on public.fr_profile_requests from anon, authenticated;
grant select (id, requested_by, name, kind, notes, status, resolved_section, created_at, updated_at)
  on public.fr_profile_requests to authenticated;
grant insert (requested_by, name, kind, notes) on public.fr_profile_requests to authenticated;
grant update (status, resolved_section, updated_at) on public.fr_profile_requests to authenticated;
grant usage, select on sequence public.fr_profile_requests_id_seq to authenticated;

create table public.fr_promotion_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  section text not null references public.fr_sections(slug) on delete cascade,
  idea_id integer references public.fr_ideas(id) on delete set null,
  placement text not null check (placement in ('profile', 'idea')),
  goal text check (goal is null or char_length(goal) <= 500),
  status text not null default 'interested' check (status in ('interested', 'eligible', 'checkout_ready', 'paid', 'cancelled')),
  organic_rank_unchanged boolean not null default true check (organic_rank_unchanged = true),
  created_at timestamptz not null default current_timestamp
);
alter table public.fr_promotion_requests enable row level security;
create policy fr_promotion_requests_owner_read on public.fr_promotion_requests
  for select to authenticated
  using (user_id = (select auth.uid()));
create policy fr_promotion_requests_eligible_insert on public.fr_promotion_requests
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and status = 'interested'
    and organic_rank_unchanged = true
    and (
      exists (
        select 1 from public.fr_platform_admins a
        where a.user_id = (select auth.uid()) and a.status = 'active'
      )
      or exists (
        select 1 from public.fr_profile_members m
        where m.user_id = (select auth.uid())
          and m.section = fr_promotion_requests.section
          and m.status = 'active'
      )
    )
  );
revoke all on public.fr_promotion_requests from anon, authenticated;
grant select (id, section, idea_id, placement, goal, status, organic_rank_unchanged, created_at)
  on public.fr_promotion_requests to authenticated;
grant insert (user_id, section, idea_id, placement, goal)
  on public.fr_promotion_requests to authenticated;
grant usage, select on sequence public.fr_promotion_requests_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('fanrank-profile-images', 'fanrank-profile-images', true, 5242880,
    array['image/jpeg', 'image/png', 'image/webp']),
  ('fanrank-owner-feedback', 'fanrank-owner-feedback', false, 8388608,
    array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy fanrank_profile_images_admin_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'fanrank-profile-images'
    and exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
create policy fanrank_profile_images_admin_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'fanrank-profile-images'
    and (storage.foldername(name))[2] = (select auth.uid())::text
    and exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
create policy fanrank_owner_feedback_admin_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'fanrank-owner-feedback'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );
create policy fanrank_owner_feedback_admin_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'fanrank-owner-feedback'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and exists (
      select 1 from public.fr_platform_admins a
      where a.user_id = (select auth.uid()) and a.status = 'active'
    )
  );

create or replace function public.fr_admin_set_profile_image(
  p_section text,
  p_path text,
  p_alt text,
  p_source_url text,
  p_credit text,
  p_rights text
)
returns table(image_path text, image_alt text, image_source_url text, image_credit text, image_rights text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
begin
  if v_actor is null or not exists (
    select 1 from public.fr_platform_admins a
    where a.user_id = v_actor and a.status = 'active'
  ) then
    raise exception using errcode = '42501', message = 'Platform administrator required';
  end if;
  if p_rights not in ('official_press', 'licensed', 'public_domain', 'owner_upload', 'generated') then
    raise exception using errcode = '22023', message = 'Image rights basis required';
  end if;
  if not exists (
    select 1 from storage.objects o
    where o.bucket_id = 'fanrank-profile-images'
      and o.name = p_path
      and o.owner_id = v_actor::text
  ) then
    raise exception using errcode = '22023', message = 'Uploaded profile image required';
  end if;

  update public.fr_sections s
  set image_path = p_path,
      image_alt = nullif(pg_catalog.btrim(p_alt), ''),
      image_source_url = nullif(pg_catalog.btrim(p_source_url), ''),
      image_credit = nullif(pg_catalog.btrim(p_credit), ''),
      image_rights = p_rights,
      image_updated_at = current_timestamp,
      image_updated_by = v_actor
  where s.slug = p_section;
  if not found then
    raise exception using errcode = '22023', message = 'Profile not found';
  end if;

  return query
  select s.image_path, s.image_alt, s.image_source_url, s.image_credit, s.image_rights
  from public.fr_sections s where s.slug = p_section;
end;
$$;
revoke all on function public.fr_admin_set_profile_image(text, text, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.fr_admin_set_profile_image(text, text, text, text, text, text)
  to authenticated;

update public.fr_sections
set featured_rank = case slug
  when 'brawl-stars' then 2
  when 'rubius' then 3
  when 'orslok' then 4
  when 'ibai' then 5
  when 'roblox' then 6
  when 'discord' then 7
  when 'x-twitter' then 8
  when 'chatgpt' then 9
  when 'claude' then 10
  else featured_rank
end
where slug in ('brawl-stars', 'rubius', 'orslok', 'ibai', 'roblox', 'discord', 'x-twitter', 'chatgpt', 'claude');

insert into public.fr_sections
  (slug, name, emoji, kind, tagline, tagline_es, tags, featured_rank, verification_status, verified_at)
values
  ('fanrank', 'FanRank', '⚡', 'company',
   'Help build the place where the best fan ideas become useful decisions.',
   'Ayuda a construir el lugar donde las mejores ideas de fans se convierten en decisiones útiles.',
   array['feedback-platform', 'community', 'ai-ranking'], 1, 'verified', current_timestamp)
on conflict (slug) do update
set name = excluded.name,
    emoji = excluded.emoji,
    kind = excluded.kind,
    tagline = excluded.tagline,
    tagline_es = excluded.tagline_es,
    tags = excluded.tags,
    featured_rank = excluded.featured_rank,
    verification_status = excluded.verification_status,
    verified_at = coalesce(public.fr_sections.verified_at, excluded.verified_at);

create or replace view public.fr_sections_stats
with (security_invoker = true)
as
select
  s.slug,
  s.name,
  s.emoji,
  s.kind,
  s.tagline,
  s.tagline_es,
  count(i.id)::integer as ideas,
  coalesce(sum(i.origin_upvotes), 0)::integer as reddit_upvotes,
  coalesce(sum(i.web_votes), 0)::integer as fan_votes,
  s.verification_status,
  s.tags,
  s.featured_rank,
  count(i.id) filter (where i.created_at >= now() - interval '30 days')::integer as recent_ideas,
  s.image_path,
  s.image_alt,
  s.image_source_url,
  s.image_credit,
  s.image_rights
from public.fr_sections s
left join public.fr_ideas i
  on i.section = s.slug and i.approved = true
group by s.slug;
grant select on public.fr_sections_stats to anon, authenticated;

alter table public.fr_events
  drop constraint if exists fr_events_event_check;
alter table public.fr_events
  add constraint fr_events_event_check
  check (event in (
    'page_view', 'search', 'profile_open', 'idea_open', 'idea_share', 'vote', 'submission',
    'section_request', 'claim_request', 'suggest_open', 'similar_vote', 'auth_open',
    'auth_link_requested', 'auth_signed_in', 'auth_signed_out', 'activity_open', 'team_interest',
    'team_invite_created', 'owner_mode_open', 'owner_feedback', 'owner_profile_request',
    'profile_image_updated', 'promotion_interest'
  ));

comment on table public.fr_promotion_requests is
  'Private launch-interest queue. No payment is taken here and organic/AI ranking must remain unchanged.';
comment on table public.fr_owner_feedback is
  'Private visual feedback from authenticated platform administrators; screenshots are stored in a private bucket.';

commit;
