-- FanRank v12: owner-managed topics with atomic per-profile limits.
-- Tiers are entitlements only: they never change organic rank, visibility, votes or stars.

begin;

alter table public.fr_sections
  add column if not exists topic_tier text not null default 'normal';

alter table public.fr_sections
  drop constraint if exists fr_sections_topic_tier_check;
alter table public.fr_sections
  add constraint fr_sections_topic_tier_check
  check (topic_tier in ('normal', 'pro', 'business', 'plus'));

create table public.fr_profile_topics (
  id bigint generated by default as identity primary key,
  section text not null references public.fr_sections(slug) on update restrict on delete cascade,
  title text not null check (pg_catalog.char_length(pg_catalog.btrim(title)) between 2 and 80),
  description text check (description is null or pg_catalog.char_length(description) <= 500),
  status text not null default 'active' check (status in ('active', 'archived')),
  sort_order integer not null default 100 check (sort_order between 0 and 10000),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now()
);

create unique index fr_profile_topics_active_title_unique
  on public.fr_profile_topics(section, pg_catalog.lower(pg_catalog.btrim(title)))
  where status = 'active';
create index fr_profile_topics_section_status_order_idx
  on public.fr_profile_topics(section, status, sort_order, id);

alter table public.fr_profile_topics enable row level security;

create policy fr_profile_topics_public_read
  on public.fr_profile_topics
  for select
  to anon, authenticated
  using (true);

revoke all on table public.fr_profile_topics from public, anon, authenticated;
grant select (id, section, title, description, status, sort_order, created_at, updated_at)
  on public.fr_profile_topics to anon, authenticated;
grant all on table public.fr_profile_topics to service_role;
grant usage, select on sequence public.fr_profile_topics_id_seq to service_role;

alter table public.fr_submissions
  add column if not exists topic_id bigint
  references public.fr_profile_topics(id) on update cascade on delete set null;
alter table public.fr_ideas
  add column if not exists topic_id bigint
  references public.fr_profile_topics(id) on update cascade on delete set null;

create index fr_ideas_topic_id_idx
  on public.fr_ideas(topic_id) where topic_id is not null;
create index fr_submissions_topic_id_idx
  on public.fr_submissions(topic_id) where topic_id is not null;
create index fr_submissions_section_status_created_idx
  on public.fr_submissions(section, status, created_at desc, id desc);

grant insert (topic_id) on public.fr_submissions to anon, authenticated, service_role;
grant select (topic_id) on public.fr_submissions to authenticated, service_role;
grant select (topic_id) on public.fr_ideas to anon, authenticated, service_role;

create or replace function fanrank_private.fr_topic_limit(p_tier text)
returns integer
language sql
immutable
set search_path = ''
as $$
  select case p_tier
    when 'normal' then 5
    when 'pro' then 20
    when 'business' then 100
    when 'plus' then 200
    else 5
  end;
$$;

create or replace function fanrank_private.fr_can_manage_profile(
  p_section text,
  p_actor uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_actor is not null and (
    exists (
      select 1
      from public.fr_platform_admins as admin_row
      where admin_row.user_id = p_actor
        and admin_row.status = 'active'
    )
    or exists (
      select 1
      from public.fr_profile_members as member_row
      join public.fr_sections as section_row on section_row.slug = member_row.section
      where member_row.user_id = p_actor
        and member_row.section = p_section
        and member_row.role in ('owner', 'admin')
        and member_row.status = 'active'
        and section_row.verification_status = 'verified'
    )
  );
$$;

revoke all on function fanrank_private.fr_topic_limit(text) from public, anon, authenticated;
revoke all on function fanrank_private.fr_can_manage_profile(text, uuid) from public, anon, authenticated;

create or replace function fanrank_private.fr_enforce_topic_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tier text;
  v_active_count integer;
begin
  if new.status <> 'active'
    or (tg_op = 'UPDATE' and old.status = 'active' and old.section = new.section)
  then
    return new;
  end if;

  select section_row.topic_tier
    into v_tier
  from public.fr_sections as section_row
  where section_row.slug = new.section
  for update;
  if v_tier is null then
    raise exception using errcode = '23503', message = 'Profile does not exist';
  end if;

  select count(*)::integer
    into v_active_count
  from public.fr_profile_topics as topic
  where topic.section = new.section
    and topic.status = 'active'
    and (tg_op = 'INSERT' or topic.id <> new.id);

  if v_active_count >= fanrank_private.fr_topic_limit(v_tier) then
    raise exception using errcode = '23514', message = 'Active topic limit reached';
  end if;
  return new;
end;
$$;

revoke all on function fanrank_private.fr_enforce_topic_limit()
  from public, anon, authenticated;
drop trigger if exists fr_profile_topics_enforce_limit on public.fr_profile_topics;
create trigger fr_profile_topics_enforce_limit
  before insert or update of section, status on public.fr_profile_topics
  for each row execute function fanrank_private.fr_enforce_topic_limit();

create or replace function fanrank_private.fr_validate_topic_assignment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_topic_section text;
  v_topic_status text;
begin
  if new.topic_id is null then
    return new;
  end if;

  select topic.section, topic.status
    into v_topic_section, v_topic_status
  from public.fr_profile_topics as topic
  where topic.id = new.topic_id;

  if v_topic_section is null then
    raise exception using errcode = '23503', message = 'Topic does not exist';
  end if;
  if v_topic_section <> new.section then
    raise exception using errcode = '23514', message = 'Topic belongs to another profile';
  end if;
  if v_topic_status <> 'active' then
    raise exception using errcode = '23514', message = 'Topic is archived';
  end if;
  return new;
end;
$$;

revoke all on function fanrank_private.fr_validate_topic_assignment()
  from public, anon, authenticated;

drop trigger if exists fr_submissions_validate_topic on public.fr_submissions;
create trigger fr_submissions_validate_topic
  before insert or update of section, topic_id on public.fr_submissions
  for each row execute function fanrank_private.fr_validate_topic_assignment();

drop trigger if exists fr_ideas_validate_topic on public.fr_ideas;
create trigger fr_ideas_validate_topic
  before insert or update of section, topic_id on public.fr_ideas
  for each row execute function fanrank_private.fr_validate_topic_assignment();

create or replace function public.fr_upsert_profile_topic(
  p_section text,
  p_topic_id bigint,
  p_title text,
  p_description text,
  p_sort_order integer
)
returns table (
  id bigint,
  section text,
  title text,
  description text,
  status text,
  sort_order integer,
  active_count integer,
  topic_limit integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_section text := pg_catalog.btrim(p_section);
  v_title text := pg_catalog.btrim(p_title);
  v_description text := nullif(pg_catalog.btrim(p_description), '');
  v_tier text;
  v_limit integer;
  v_active_count integer;
  v_existing_status text;
  v_topic public.fr_profile_topics%rowtype;
begin
  if v_actor is null then
    raise exception using errcode = '42501', message = 'Authenticated profile manager required';
  end if;
  if v_section is null or pg_catalog.char_length(v_section) not between 1 and 120
    or v_title is null or pg_catalog.char_length(v_title) not between 2 and 80
    or (v_description is not null and pg_catalog.char_length(v_description) > 500)
    or coalesce(p_sort_order, 100) not between 0 and 10000
  then
    raise exception using errcode = '22023', message = 'Valid topic fields required';
  end if;

  select section_row.topic_tier
    into v_tier
  from public.fr_sections as section_row
  where section_row.slug = v_section
  for update;

  if v_tier is null then
    raise exception using errcode = '22023', message = 'Profile does not exist';
  end if;
  if not fanrank_private.fr_can_manage_profile(v_section, v_actor) then
    raise exception using errcode = '42501', message = 'Verified profile owner or administrator required';
  end if;

  v_limit := fanrank_private.fr_topic_limit(v_tier);
  select count(*)::integer
    into v_active_count
  from public.fr_profile_topics as topic
  where topic.section = v_section
    and topic.status = 'active';

  if p_topic_id is null then
    if v_active_count >= v_limit then
      raise exception using errcode = '23514', message = 'Active topic limit reached';
    end if;
    insert into public.fr_profile_topics (
      section, title, description, status, sort_order, created_by, updated_by
    ) values (
      v_section, v_title, v_description, 'active', coalesce(p_sort_order, 100), v_actor, v_actor
    ) returning * into v_topic;
    v_active_count := v_active_count + 1;
  else
    select topic.status
      into v_existing_status
    from public.fr_profile_topics as topic
    where topic.id = p_topic_id
      and topic.section = v_section
    for update;
    if v_existing_status is null then
      raise exception using errcode = '22023', message = 'Topic does not belong to this profile';
    end if;
    if v_existing_status <> 'active' then
      raise exception using errcode = '22023', message = 'Archived topics cannot be edited';
    end if;
    update public.fr_profile_topics as topic
      set title = v_title,
          description = v_description,
          sort_order = coalesce(p_sort_order, 100),
          updated_by = v_actor,
          updated_at = pg_catalog.now()
    where topic.id = p_topic_id
      and topic.section = v_section
    returning topic.* into v_topic;
  end if;

  return query select
    v_topic.id, v_topic.section, v_topic.title, v_topic.description,
    v_topic.status, v_topic.sort_order, v_active_count, v_limit;
end;
$$;

create or replace function public.fr_archive_profile_topic(
  p_section text,
  p_topic_id bigint
)
returns table (
  id bigint,
  status text,
  active_count integer,
  topic_limit integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_section text := pg_catalog.btrim(p_section);
  v_tier text;
  v_active_count integer;
begin
  if v_actor is null then
    raise exception using errcode = '42501', message = 'Authenticated profile manager required';
  end if;
  select section_row.topic_tier
    into v_tier
  from public.fr_sections as section_row
  where section_row.slug = v_section
  for update;
  if v_tier is null then
    raise exception using errcode = '22023', message = 'Profile does not exist';
  end if;
  if not fanrank_private.fr_can_manage_profile(v_section, v_actor) then
    raise exception using errcode = '42501', message = 'Verified profile owner or administrator required';
  end if;

  update public.fr_profile_topics as topic
    set status = 'archived', updated_by = v_actor, updated_at = pg_catalog.now()
  where topic.id = p_topic_id
    and topic.section = v_section
    and topic.status = 'active';
  if not found then
    raise exception using errcode = '22023', message = 'Active topic does not belong to this profile';
  end if;

  select count(*)::integer
    into v_active_count
  from public.fr_profile_topics as topic
  where topic.section = v_section
    and topic.status = 'active';

  return query select p_topic_id, 'archived'::text, v_active_count,
    fanrank_private.fr_topic_limit(v_tier);
end;
$$;

create or replace function public.fr_set_idea_topic(
  p_idea_id integer,
  p_topic_id bigint
)
returns table (
  idea_id integer,
  section text,
  topic_id bigint,
  topic_title text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_section text;
  v_topic_title text;
begin
  if v_actor is null then
    raise exception using errcode = '42501', message = 'Authenticated profile manager required';
  end if;
  select idea.section
    into v_section
  from public.fr_ideas as idea
  where idea.id = p_idea_id
  for update;
  if v_section is null then
    raise exception using errcode = '22023', message = 'Idea does not exist';
  end if;
  perform 1 from public.fr_sections as section_row where section_row.slug = v_section for update;
  if not fanrank_private.fr_can_manage_profile(v_section, v_actor) then
    raise exception using errcode = '42501', message = 'Verified profile owner or administrator required';
  end if;

  if p_topic_id is not null then
    select topic.title
      into v_topic_title
    from public.fr_profile_topics as topic
    where topic.id = p_topic_id
      and topic.section = v_section
      and topic.status = 'active';
    if v_topic_title is null then
      raise exception using errcode = '22023', message = 'Active topic does not belong to this profile';
    end if;
  end if;

  update public.fr_ideas as idea
    set topic_id = p_topic_id
  where idea.id = p_idea_id;

  return query select p_idea_id, v_section, p_topic_id, v_topic_title;
end;
$$;

revoke all on function public.fr_upsert_profile_topic(text, bigint, text, text, integer)
  from public, anon, authenticated;
revoke all on function public.fr_archive_profile_topic(text, bigint)
  from public, anon, authenticated;
revoke all on function public.fr_set_idea_topic(integer, bigint)
  from public, anon, authenticated;
grant execute on function public.fr_upsert_profile_topic(text, bigint, text, text, integer)
  to authenticated;
grant execute on function public.fr_archive_profile_topic(text, bigint)
  to authenticated;
grant execute on function public.fr_set_idea_topic(integer, bigint)
  to authenticated;

create or replace view public.fr_profile_topics_public
with (security_invoker = true)
as
select id, section, title, description, status, sort_order, created_at, updated_at
from public.fr_profile_topics;

revoke all on public.fr_profile_topics_public from public, anon, authenticated;
grant select on public.fr_profile_topics_public to anon, authenticated;

create or replace view public.fr_ranking
with (security_invoker = true)
as
select
  idea.id,
  idea.section,
  idea.title,
  idea.title_es,
  idea.source_url,
  idea.origin_upvotes,
  idea.ai_score,
  idea.ai_reason,
  idea.ai_reason_es,
  idea.owner_pick,
  idea.web_votes,
  idea.team_interest_count,
  idea.owner_star_value,
  idea.team_star_support_count,
  idea.topic_id,
  topic.title as topic_title,
  topic.status as topic_status
from public.fr_ideas as idea
left join public.fr_profile_topics as topic on topic.id = idea.topic_id
where idea.approved = true;

revoke all on public.fr_ranking from public, anon, authenticated;
grant select on public.fr_ranking to anon, authenticated;

create or replace view public.fr_sections_stats
with (security_invoker = true)
as
select
  section_row.slug,
  section_row.name,
  section_row.emoji,
  section_row.kind,
  section_row.tagline,
  section_row.tagline_es,
  count(idea.id)::integer as ideas,
  coalesce(sum(idea.origin_upvotes), 0::bigint)::integer as reddit_upvotes,
  coalesce(sum(idea.web_votes), 0::bigint)::integer as fan_votes,
  section_row.verification_status,
  section_row.tags,
  section_row.featured_rank,
  count(idea.id) filter (where idea.created_at >= pg_catalog.now() - interval '30 days')::integer as recent_ideas,
  section_row.image_path,
  section_row.image_alt,
  section_row.image_source_url,
  section_row.image_credit,
  section_row.image_rights,
  section_row.team_member_star_cap,
  section_row.topic_tier,
  case section_row.topic_tier
    when 'normal' then 5
    when 'pro' then 20
    when 'business' then 100
    when 'plus' then 200
    else 5
  end::integer as topic_limit,
  (
    select count(*)::integer
    from public.fr_profile_topics as topic
    where topic.section = section_row.slug
      and topic.status = 'active'
  ) as topic_active_count
from public.fr_sections as section_row
left join public.fr_ideas as idea
  on idea.section = section_row.slug
  and idea.approved = true
group by section_row.slug;

revoke all on public.fr_sections_stats from public, anon, authenticated;
grant select on public.fr_sections_stats to anon, authenticated;

drop function if exists public.fr_team_submission_inbox(text, integer);
create function public.fr_team_submission_inbox(
  p_section text,
  p_limit integer default 50
)
returns table (
  id bigint,
  section text,
  title text,
  details text,
  author text,
  contact text,
  language text,
  status text,
  canonical_idea_id integer,
  category_requested text,
  category_final text,
  classification_method text,
  attachment_count smallint,
  evidence_links text[],
  can_contact boolean,
  topic_id bigint,
  topic_title text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_section text := pg_catalog.btrim(p_section);
  v_limit integer := least(greatest(coalesce(p_limit, 50), 1), 50);
  v_authorized boolean;
begin
  if v_actor is null then
    raise exception using errcode = '42501', message = 'Authenticated team member required';
  end if;
  if v_section is null or pg_catalog.char_length(v_section) not between 1 and 120 then
    raise exception using errcode = '22023', message = 'Valid profile section required';
  end if;

  select fanrank_private.fr_can_manage_profile(v_section, v_actor) into v_authorized;
  if not coalesce(v_authorized, false) then
    raise exception using errcode = '42501', message = 'Verified profile owner or administrator required';
  end if;

  return query
  select
    submission.id,
    submission.section,
    submission.title,
    submission.details,
    case when submission.allow_contact then submission.author else null end,
    case when submission.allow_contact then submission.contact else null end,
    submission.language,
    submission.status,
    submission.canonical_idea_id,
    submission.category_requested,
    submission.category_final,
    submission.classification_method,
    submission.attachment_count,
    submission.evidence_links,
    submission.allow_contact,
    submission.topic_id,
    topic.title,
    submission.created_at
  from public.fr_submissions as submission
  left join public.fr_profile_topics as topic on topic.id = submission.topic_id
  where submission.section = v_section
    and submission.status = 'received'
  order by submission.created_at desc, submission.id desc
  limit v_limit;
end;
$$;

revoke all on function public.fr_team_submission_inbox(text, integer)
  from public, anon, authenticated;
grant execute on function public.fr_team_submission_inbox(text, integer)
  to authenticated;

alter table public.fr_events
  drop constraint if exists fr_events_event_check;
alter table public.fr_events
  add constraint fr_events_event_check
  check (event in (
    'page_view', 'search', 'profile_open', 'idea_open', 'idea_share', 'vote', 'submission',
    'section_request', 'claim_request', 'suggest_open', 'similar_vote', 'auth_open',
    'auth_link_requested', 'auth_recovery_requested', 'auth_signed_in', 'auth_signed_out',
    'activity_open', 'team_interest', 'team_star', 'team_star_cap', 'team_invite_created',
    'owner_mode_open', 'owner_feedback', 'owner_profile_request', 'profile_image_updated',
    'promotion_interest', 'pro_interest', 'media_added', 'fan_profile_saved', 'fan_profile_open',
    'owner_cta_open', 'topic_filter', 'topic_created', 'topic_archived', 'topic_assigned'
  ));

comment on table public.fr_profile_topics is
  'Verified profile topics. Active-topic caps are enforced atomically per profile and never affect organic ranking.';
comment on column public.fr_sections.topic_tier is
  'Internal topic entitlement: normal=5, pro=20, business=100, plus=200 active topics. Not a ranking signal.';
comment on function public.fr_upsert_profile_topic(text, bigint, text, text, integer) is
  'Creates or edits one active topic for an authorized verified profile owner/admin under an atomic profile-level cap.';

commit;
